/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './ng2-jsgrid.component';
const styles_JsGridComponent:any[] = ([] as any[]);
export const RenderType_JsGridComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_JsGridComponent,
  data: {}
}
);
export function View_JsGridComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),0,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n    ']))
  ]
  ,(null as any),(null as any));
}
function View_JsGridComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'js-grid',([] as any[]),(null as any),(null as any),(null as any),View_JsGridComponent_0,RenderType_JsGridComponent)),
    import0.ɵdid(4308992,(null as any),0,import1.JsGridComponent,[import0.ElementRef],(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const JsGridComponentNgFactory:import0.ComponentFactory<import1.JsGridComponent> = import0.ɵccf('js-grid',import1.JsGridComponent,View_JsGridComponent_Host_0,{
  options: 'options',
  source: 'source'
}
,{pageChanged: 'pageChanged'},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvRElOSCBEVU9ORy9Eb2N1bWVudHMvR2l0aHViL25nMi1qc2dyaWQvc3JjL25nMi1qc2dyaWQvbmcyLWpzZ3JpZC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvRElOSCBEVU9ORy9Eb2N1bWVudHMvR2l0aHViL25nMi1qc2dyaWQvc3JjL25nMi1qc2dyaWQvbmcyLWpzZ3JpZC5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9ESU5IIERVT05HL0RvY3VtZW50cy9HaXRodWIvbmcyLWpzZ3JpZC9zcmMvbmcyLWpzZ3JpZC9uZzItanNncmlkLmNvbXBvbmVudC50cy5Kc0dyaWRDb21wb25lbnQuaHRtbCIsIm5nOi8vL0M6L1VzZXJzL0RJTkggRFVPTkcvRG9jdW1lbnRzL0dpdGh1Yi9uZzItanNncmlkL3NyYy9uZzItanNncmlkL25nMi1qc2dyaWQuY29tcG9uZW50LnRzLkpzR3JpZENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgIDxkaXY+PC9kaXY+XG4gICAgIiwiPGpzLWdyaWQ+PC9qcy1ncmlkPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtJQUNJO0lBQVc7Ozs7OztJQ0RmO2dCQUFBOzs7SUFBQTs7Ozs7OzsifQ==
